// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A base for all symbol information.
    /// </summary>
    [DataContract]
    public record BaseSymbolInformation
    {
        [JsonConstructor]
        public BaseSymbolInformation(
            string name,
            SymbolKind kind,
            ImmutableArray<SymbolTag> tags = default!,
            string? containerName = null
        )
        {
            Name = name;
            Kind = kind;
            Tags = tags;
            ContainerName = containerName;
        }
        /// <summary>
        /// The name of this symbol.
        /// </summary>
        [DataMember(Name = "name")]
        public string Name { get; init; }
        /// <summary>
        /// The kind of this symbol.
        /// </summary>
        [DataMember(Name = "kind")]
        public SymbolKind Kind { get; init; }
        /// <summary>
        /// Tags for this symbol.
        /// 
        /// </summary>
        [Since("3.16.0")]
        [JsonConverter(typeof(CustomArrayConverter<SymbolTag>))]
        [DataMember(Name = "tags")]
        public ImmutableArray<SymbolTag> Tags { get; init; }
        /// <summary>
        /// The name of the symbol containing this symbol. This information is for
        /// user interface purposes (e.g. to render a qualifier in the user interface
        /// if necessary). It can't be used to re-infer a hierarchy for the document
        /// symbols.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "containerName")]
        public string? ContainerName { get; init; }
    }

}
