// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record ChangeAnnotationsSupportOptions
    {
        [JsonConstructor]
        public ChangeAnnotationsSupportOptions(
            bool? groupsOnLabel = null
        )
        {
            GroupsOnLabel = groupsOnLabel;
        }
        /// <summary>
        /// Whether the client groups edits with equal labels into tree nodes,
        /// for instance all edits labelled with "Changes in Strings" would
        /// be a tree node.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "groupsOnLabel")]
        public bool? GroupsOnLabel { get; init; }
    }

}
