// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record ClientSemanticTokensRequestFullDelta
    {
        [JsonConstructor]
        public ClientSemanticTokensRequestFullDelta(
            bool? delta = null
        )
        {
            Delta = delta;
        }
        /// <summary>
        /// The client will send the `textDocument/semanticTokens/full/delta` request if
        /// the server provides a corresponding handler.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "delta")]
        public bool? Delta { get; init; }
    }

}
