// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Defines the capabilities provided by the client.
    /// </summary>
    [DataContract]
    public record ClientCapabilities
    {
        [JsonConstructor]
        public ClientCapabilities(
            WorkspaceClientCapabilities? workspace = null,
            TextDocumentClientCapabilities? textDocument = null,
            NotebookDocumentClientCapabilities? notebookDocument = null,
            WindowClientCapabilities? window = null,
            GeneralClientCapabilities? general = null,
            LSPAny? experimental = null
        )
        {
            Workspace = workspace;
            TextDocument = textDocument;
            NotebookDocument = notebookDocument;
            Window = window;
            General = general;
            Experimental = experimental;
        }
        /// <summary>
        /// Workspace specific client capabilities.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workspace")]
        public WorkspaceClientCapabilities? Workspace { get; init; }
        /// <summary>
        /// Text document specific client capabilities.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "textDocument")]
        public TextDocumentClientCapabilities? TextDocument { get; init; }
        /// <summary>
        /// Capabilities specific to the notebook document support.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "notebookDocument")]
        public NotebookDocumentClientCapabilities? NotebookDocument { get; init; }
        /// <summary>
        /// Window specific client capabilities.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "window")]
        public WindowClientCapabilities? Window { get; init; }
        /// <summary>
        /// General client capabilities.
        /// 
        /// </summary>
        [Since("3.16.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "general")]
        public GeneralClientCapabilities? General { get; init; }
        /// <summary>
        /// Experimental client capabilities.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "experimental")]
        public LSPAny? Experimental { get; init; }
    }

}
