// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record ClientSymbolKindOptions
    {
        [JsonConstructor]
        public ClientSymbolKindOptions(
            ImmutableArray<SymbolKind> valueSet = default!
        )
        {
            ValueSet = valueSet;
        }
        /// <summary>
        /// The symbol kind values the client supports. When this
        /// property exists the client also guarantees that it will
        /// handle values outside its set gracefully and falls back
        /// to a default value when unknown.
        /// 
        /// If this property is not present the client only supports
        /// the symbol kinds from `File` to `Array` as defined in
        /// the initial version of the protocol.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<SymbolKind>))]
        [DataMember(Name = "valueSet")]
        public ImmutableArray<SymbolKind> ValueSet { get; init; }
    }

}
