// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record ClientSignatureInformationOptions
    {
        [JsonConstructor]
        public ClientSignatureInformationOptions(
            ImmutableArray<MarkupKind> documentationFormat = default!,
            ClientSignatureParameterInformationOptions? parameterInformation = null,
            bool? activeParameterSupport = null,
            bool? noActiveParameterSupport = null
        )
        {
            DocumentationFormat = documentationFormat;
            ParameterInformation = parameterInformation;
            ActiveParameterSupport = activeParameterSupport;
            NoActiveParameterSupport = noActiveParameterSupport;
        }
        /// <summary>
        /// Client supports the following content formats for the documentation
        /// property. The order describes the preferred format of the client.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<MarkupKind>))]
        [DataMember(Name = "documentationFormat")]
        public ImmutableArray<MarkupKind> DocumentationFormat { get; init; }
        /// <summary>
        /// Client capabilities specific to parameter information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "parameterInformation")]
        public ClientSignatureParameterInformationOptions? ParameterInformation { get; init; }
        /// <summary>
        /// The client supports the `activeParameter` property on `SignatureInformation`
        /// literal.
        /// 
        /// </summary>
        [Since("3.16.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "activeParameterSupport")]
        public bool? ActiveParameterSupport { get; init; }
        /// <summary>
        /// The client supports the `activeParameter` property on
        /// `SignatureHelp`/`SignatureInformation` being set to `null` to
        /// indicate that no parameter should be active.
        /// 
        /// </summary>
        [Proposed]
        [Since("3.18.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "noActiveParameterSupport")]
        public bool? NoActiveParameterSupport { get; init; }
    }

}
