// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Structure to capture a description for an error code.
    /// 
    /// </summary>
    [Since("3.16.0")]
    [DataContract]
    public record CodeDescription
    {
        [JsonConstructor]
        public CodeDescription(
            Uri href
        )
        {
            Href = href;
        }
        /// <summary>
        /// An URI to open with more information about the diagnostic error.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "href")]
        public Uri Href { get; init; }
    }

}
