// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Represents a color in RGBA space.
    /// </summary>
    [DataContract]
    public record Color
    {
        [JsonConstructor]
        public Color(
            float red,
            float green,
            float blue,
            float alpha
        )
        {
            Red = red;
            Green = green;
            Blue = blue;
            Alpha = alpha;
        }
        /// <summary>
        /// The red component of this color in the range [0-1].
        /// </summary>
        [DataMember(Name = "red")]
        public float Red { get; init; }
        /// <summary>
        /// The green component of this color in the range [0-1].
        /// </summary>
        [DataMember(Name = "green")]
        public float Green { get; init; }
        /// <summary>
        /// The blue component of this color in the range [0-1].
        /// </summary>
        [DataMember(Name = "blue")]
        public float Blue { get; init; }
        /// <summary>
        /// The alpha component of this color in the range [0-1].
        /// </summary>
        [DataMember(Name = "alpha")]
        public float Alpha { get; init; }
    }

}
