// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The client supports the following `CompletionList` specific
    /// capabilities.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record CompletionListCapabilities
    {
        [JsonConstructor]
        public CompletionListCapabilities(
            ImmutableArray<string> itemDefaults = default!
        )
        {
            ItemDefaults = itemDefaults;
        }
        /// <summary>
        /// The client supports the following itemDefaults on
        /// a completion list.
        /// 
        /// The value lists the supported property names of the
        /// `CompletionList.itemDefaults` object. If omitted
        /// no properties are supported.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [JsonConverter(typeof(CustomArrayConverter<string>))]
        [DataMember(Name = "itemDefaults")]
        public ImmutableArray<string> ItemDefaults { get; init; }
    }

}
