// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// In many cases the items of an actual completion result share the same
    /// value for properties like `commitCharacters` or the range of a text
    /// edit. A completion list can therefore define item defaults which will
    /// be used if a completion item itself doesn't specify the value.
    /// 
    /// If a completion list specifies a default value and a completion item
    /// also specifies a corresponding value the one from the item is used.
    /// 
    /// Servers are only allowed to return default values if the client
    /// signals support for this via the `completionList.itemDefaults`
    /// capability.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record CompletionItemDefaults
    {
        [JsonConstructor]
        public CompletionItemDefaults(
            ImmutableArray<string> commitCharacters = default!,
            OrType<Range, EditRangeWithInsertReplace>? editRange = null,
            InsertTextFormat? insertTextFormat = null,
            InsertTextMode? insertTextMode = null,
            LSPAny? data = null
        )
        {
            CommitCharacters = commitCharacters;
            EditRange = editRange;
            InsertTextFormat = insertTextFormat;
            InsertTextMode = insertTextMode;
            Data = data;
        }
        /// <summary>
        /// A default commit character set.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [JsonConverter(typeof(CustomArrayConverter<string>))]
        [DataMember(Name = "commitCharacters")]
        public ImmutableArray<string> CommitCharacters { get; init; }
        /// <summary>
        /// A default edit range.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [JsonConverter(typeof(OrTypeConverter<Range, EditRangeWithInsertReplace>))]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "editRange")]
        public OrType<Range, EditRangeWithInsertReplace>? EditRange { get; init; }
        /// <summary>
        /// A default insert text format.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "insertTextFormat")]
        public InsertTextFormat? InsertTextFormat { get; init; }
        /// <summary>
        /// A default insert text mode.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "insertTextMode")]
        public InsertTextMode? InsertTextMode { get; init; }
        /// <summary>
        /// A default data value.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "data")]
        public LSPAny? Data { get; init; }
    }

}
