// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record ConfigurationItem
    {
        [JsonConstructor]
        public ConfigurationItem(
            Uri? scopeUri = null,
            string? section = null
        )
        {
            ScopeUri = scopeUri;
            Section = section;
        }
        /// <summary>
        /// The scope to get the configuration section for.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "scopeUri")]
        public Uri? ScopeUri { get; init; }
        /// <summary>
        /// The configuration section asked for.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "section")]
        public string? Section { get; init; }
    }

}
