// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The declaration of a symbol representation as one or many <see cref="Location">locations</see>.
    /// </summary>
    [JsonConverter(typeof(DeclarationConverter))]
    [DataContract]
    public record Declaration: OrType<Location, ImmutableArray<Location>>
    {
        public Declaration(Location Location): base(Location) {}
        public Declaration(ImmutableArray<Location> locations): base(locations) {}
    }

}
