// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;

namespace Microsoft.LanguageServer.Protocol {
    public class DeclarationConverter : JsonConverter<Declaration>
    {
    private OrTypeConverter<Location,ImmutableArray<Location>> _orType;
    public DeclarationConverter()
    {
    _orType = new OrTypeConverter<Location,ImmutableArray<Location>>();
    }
    public override Declaration? ReadJson(JsonReader reader, Type objectType, Declaration? existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
    reader = reader ?? throw new ArgumentNullException(nameof(reader));
    if (reader.TokenType == JsonToken.Null) { return null; }
    var o = _orType.ReadJson(reader, objectType, existingValue, serializer);
    if (o is OrType<Location,ImmutableArray<Location>> orType)
    {
    if (orType.Value?.GetType() == typeof(Location))
    {
    return new Declaration((Location)orType.Value);
    }
    if (orType.Value?.GetType() == typeof(ImmutableArray<Location>))
    {
    return new Declaration((ImmutableArray<Location>)orType.Value);
    }
    }
    throw new JsonSerializationException($"Unexpected token type.");
    }
    public override void WriteJson(JsonWriter writer, Declaration? value, JsonSerializer serializer)
    {
    _orType.WriteJson(writer, value, serializer);
    }
    }
}
