// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Delete file options
    /// </summary>
    [DataContract]
    public record DeleteFileOptions
    {
        [JsonConstructor]
        public DeleteFileOptions(
            bool? recursive = null,
            bool? ignoreIfNotExists = null
        )
        {
            Recursive = recursive;
            IgnoreIfNotExists = ignoreIfNotExists;
        }
        /// <summary>
        /// Delete the content recursively if a folder is denoted.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "recursive")]
        public bool? Recursive { get; init; }
        /// <summary>
        /// Ignore the operation if the file doesn't exist.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "ignoreIfNotExists")]
        public bool? IgnoreIfNotExists { get; init; }
    }

}
