// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Diagnostic options.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record DiagnosticOptions
    {
        [JsonConstructor]
        public DiagnosticOptions(
            bool interFileDependencies,
            bool workspaceDiagnostics,
            string? identifier = null,
            bool? workDoneProgress = null
        )
        {
            Identifier = identifier;
            InterFileDependencies = interFileDependencies;
            WorkspaceDiagnostics = workspaceDiagnostics;
            WorkDoneProgress = workDoneProgress;
        }
        /// <summary>
        /// An optional identifier under which the diagnostics are
        /// managed by the client.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "identifier")]
        public string? Identifier { get; init; }
        /// <summary>
        /// Whether the language has inter file dependencies meaning that
        /// editing code in one file can result in a different diagnostic
        /// set in another file. Inter file dependencies are common for
        /// most programming languages and typically uncommon for linters.
        /// </summary>
        [DataMember(Name = "interFileDependencies")]
        public bool InterFileDependencies { get; init; }
        /// <summary>
        /// The server provides support for workspace diagnostics as well.
        /// </summary>
        [DataMember(Name = "workspaceDiagnostics")]
        public bool WorkspaceDiagnostics { get; init; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
    }

}
