// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Describe options to be used when registered for text document change events.
    /// </summary>
    [DataContract]
    public record DidChangeWatchedFilesRegistrationOptions
    {
        [JsonConstructor]
        public DidChangeWatchedFilesRegistrationOptions(
            ImmutableArray<FileSystemWatcher> watchers
        )
        {
            Watchers = watchers;
        }
        /// <summary>
        /// The watchers to register.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<FileSystemWatcher>))]
        [DataMember(Name = "watchers")]
        public ImmutableArray<FileSystemWatcher> Watchers { get; init; }
    }

}
