// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record DidChangeConfigurationRegistrationOptions
    {
        [JsonConstructor]
        public DidChangeConfigurationRegistrationOptions(
            OrType<string, ImmutableArray<string>>? section = null
        )
        {
            Section = section;
        }
        [JsonConverter(typeof(OrTypeConverter<string, ImmutableArray<string>>))]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "section")]
        public OrType<string, ImmutableArray<string>>? Section { get; init; }
    }

}
