// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The params sent in a close notebook document notification.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record DidCloseNotebookDocumentParams
    {
        [JsonConstructor]
        public DidCloseNotebookDocumentParams(
            NotebookDocumentIdentifier notebookDocument,
            ImmutableArray<TextDocumentIdentifier> cellTextDocuments
        )
        {
            NotebookDocument = notebookDocument;
            CellTextDocuments = cellTextDocuments;
        }
        /// <summary>
        /// The notebook document that got closed.
        /// </summary>
        [DataMember(Name = "notebookDocument")]
        public NotebookDocumentIdentifier NotebookDocument { get; init; }
        /// <summary>
        /// The text documents that represent the content
        /// of a notebook cell that got closed.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<TextDocumentIdentifier>))]
        [DataMember(Name = "cellTextDocuments")]
        public ImmutableArray<TextDocumentIdentifier> CellTextDocuments { get; init; }
    }

}
