// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The parameters of a <see cref="DocumentOnTypeFormattingRequest" />.
    /// </summary>
    [DataContract]
    public record DocumentOnTypeFormattingParams
    {
        [JsonConstructor]
        public DocumentOnTypeFormattingParams(
            TextDocumentIdentifier textDocument,
            Position position,
            string ch,
            FormattingOptions options
        )
        {
            TextDocument = textDocument;
            Position = position;
            Ch = ch;
            Options = options;
        }
        /// <summary>
        /// The document to format.
        /// </summary>
        [DataMember(Name = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; init; }
        /// <summary>
        /// The position around which the on type formatting should happen.
        /// This is not necessarily the exact position where the character denoted
        /// by the property `ch` got typed.
        /// </summary>
        [DataMember(Name = "position")]
        public Position Position { get; init; }
        /// <summary>
        /// The character that has been typed that triggered the formatting
        /// on type request. That is not necessarily the last character that
        /// got inserted into the document since the client could auto insert
        /// characters as well (e.g. like automatic brace completion).
        /// </summary>
        [DataMember(Name = "ch")]
        public string Ch { get; init; }
        /// <summary>
        /// The formatting options.
        /// </summary>
        [DataMember(Name = "options")]
        public FormattingOptions Options { get; init; }
    }

}
