// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A document link is a range in a text document that links to an internal or external resource, like another
    /// text document or a web site.
    /// </summary>
    [DataContract]
    public record DocumentLink
    {
        [JsonConstructor]
        public DocumentLink(
            Range range,
            Uri? target = null,
            string? tooltip = null,
            LSPAny? data = null
        )
        {
            Range = range;
            Target = target;
            Tooltip = tooltip;
            Data = data;
        }
        /// <summary>
        /// The range this link applies to.
        /// </summary>
        [DataMember(Name = "range")]
        public Range Range { get; init; }
        /// <summary>
        /// The uri this link points to. If missing a resolve request is sent later.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "target")]
        public Uri? Target { get; init; }
        /// <summary>
        /// The tooltip text when you hover over this link.
        /// 
        /// If a tooltip is provided, is will be displayed in a string that includes instructions on how to
        /// trigger the link, such as `{0} (ctrl + click)`. The specific instructions vary depending on OS,
        /// user settings, and localization.
        /// 
        /// </summary>
        [Since("3.15.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "tooltip")]
        public string? Tooltip { get; init; }
        /// <summary>
        /// A data entry field that is preserved on a document link between a
        /// DocumentLinkRequest and a DocumentLinkResolveRequest.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "data")]
        public LSPAny? Data { get; init; }
    }

}
