// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The parameters of a <see cref="DocumentRangeFormattingRequest" />.
    /// </summary>
    [DataContract]
    public record DocumentRangeFormattingParams
    {
        [JsonConstructor]
        public DocumentRangeFormattingParams(
            TextDocumentIdentifier textDocument,
            Range range,
            FormattingOptions options,
            ProgressToken? workDoneToken = null
        )
        {
            TextDocument = textDocument;
            Range = range;
            Options = options;
            WorkDoneToken = workDoneToken;
        }
        /// <summary>
        /// The document to format.
        /// </summary>
        [DataMember(Name = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; init; }
        /// <summary>
        /// The range to format
        /// </summary>
        [DataMember(Name = "range")]
        public Range Range { get; init; }
        /// <summary>
        /// The format options
        /// </summary>
        [DataMember(Name = "options")]
        public FormattingOptions Options { get; init; }
        /// <summary>
        /// An optional token that a server can use to report work done progress.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneToken")]
        public ProgressToken? WorkDoneToken { get; init; }
    }

}
