// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [JsonConverter(typeof(DocumentDiagnosticReportPartialResultRelatedDocumentsValueConverter))]
    [DataContract]
    public record DocumentDiagnosticReportPartialResultRelatedDocumentsValue: OrType<FullDocumentDiagnosticReport, UnchangedDocumentDiagnosticReport>
    {
        public DocumentDiagnosticReportPartialResultRelatedDocumentsValue(FullDocumentDiagnosticReport FullDocumentDiagnosticReport): base(FullDocumentDiagnosticReport) {}
        public DocumentDiagnosticReportPartialResultRelatedDocumentsValue(UnchangedDocumentDiagnosticReport UnchangedDocumentDiagnosticReport): base(UnchangedDocumentDiagnosticReport) {}
    }

}
