// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Registration options for a <see cref="DocumentSymbolRequest" />.
    /// </summary>
    [DataContract]
    public record DocumentSymbolRegistrationOptions
    {
        [JsonConstructor]
        public DocumentSymbolRegistrationOptions(
            DocumentSelector? documentSelector = null,
            string? label = null,
            bool? workDoneProgress = null
        )
        {
            DocumentSelector = documentSelector;
            Label = label;
            WorkDoneProgress = workDoneProgress;
        }
        /// <summary>
        /// A document selector to identify the scope of the registration. If set to null
        /// the document selector provided on the client side will be used.
        /// </summary>
        [JsonConverter(typeof(DocumentSelectorConverter))]
        [DataMember(Name = "documentSelector")]
        public DocumentSelector? DocumentSelector { get; init; }
        /// <summary>
        /// A human-readable string that is shown when multiple outlines trees
        /// are shown for the same document.
        /// 
        /// </summary>
        [Since("3.16.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "label")]
        public string? Label { get; init; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
    }

}
