// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Provider options for a <see cref="DocumentOnTypeFormattingRequest" />.
    /// </summary>
    [DataContract]
    public record DocumentOnTypeFormattingOptions
    {
        [JsonConstructor]
        public DocumentOnTypeFormattingOptions(
            string firstTriggerCharacter,
            ImmutableArray<string> moreTriggerCharacter = default!
        )
        {
            FirstTriggerCharacter = firstTriggerCharacter;
            MoreTriggerCharacter = moreTriggerCharacter;
        }
        /// <summary>
        /// A character on which formatting should be triggered, like `{`.
        /// </summary>
        [DataMember(Name = "firstTriggerCharacter")]
        public string FirstTriggerCharacter { get; init; }
        /// <summary>
        /// More trigger characters.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<string>))]
        [DataMember(Name = "moreTriggerCharacter")]
        public ImmutableArray<string> MoreTriggerCharacter { get; init; }
    }

}
