// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The result of a document diagnostic pull request. A report can
    /// either be a full report containing all diagnostics for the
    /// requested document or an unchanged report indicating that nothing
    /// has changed in terms of diagnostics in comparison to the last
    /// pull request.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [JsonConverter(typeof(DocumentDiagnosticReportConverter))]
    [DataContract]
    public record DocumentDiagnosticReport: OrType<RelatedFullDocumentDiagnosticReport, RelatedUnchangedDocumentDiagnosticReport>
    {
        public DocumentDiagnosticReport(RelatedFullDocumentDiagnosticReport RelatedFullDocumentDiagnosticReport): base(RelatedFullDocumentDiagnosticReport) {}
        public DocumentDiagnosticReport(RelatedUnchangedDocumentDiagnosticReport RelatedUnchangedDocumentDiagnosticReport): base(RelatedUnchangedDocumentDiagnosticReport) {}
    }

}
