// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A partial result for a document diagnostic report.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record DocumentDiagnosticReportPartialResult
    {
        [JsonConstructor]
        public DocumentDiagnosticReportPartialResult(
            ImmutableDictionary<Uri, DocumentDiagnosticReportPartialResultRelatedDocumentsValue> relatedDocuments
        )
        {
            RelatedDocuments = relatedDocuments;
        }
        [DataMember(Name = "relatedDocuments")]
        public ImmutableDictionary<Uri, DocumentDiagnosticReportPartialResultRelatedDocumentsValue> RelatedDocuments { get; init; }
    }

}
