// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;

namespace Microsoft.LanguageServer.Protocol {
    public class DocumentDiagnosticReportConverter : JsonConverter<DocumentDiagnosticReport>
    {
    private OrTypeConverter<RelatedFullDocumentDiagnosticReport,RelatedUnchangedDocumentDiagnosticReport> _orType;
    public DocumentDiagnosticReportConverter()
    {
    _orType = new OrTypeConverter<RelatedFullDocumentDiagnosticReport,RelatedUnchangedDocumentDiagnosticReport>();
    }
    public override DocumentDiagnosticReport? ReadJson(JsonReader reader, Type objectType, DocumentDiagnosticReport? existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
    reader = reader ?? throw new ArgumentNullException(nameof(reader));
    if (reader.TokenType == JsonToken.Null) { return null; }
    var o = _orType.ReadJson(reader, objectType, existingValue, serializer);
    if (o is OrType<RelatedFullDocumentDiagnosticReport,RelatedUnchangedDocumentDiagnosticReport> orType)
    {
    if (orType.Value?.GetType() == typeof(RelatedFullDocumentDiagnosticReport))
    {
    return new DocumentDiagnosticReport((RelatedFullDocumentDiagnosticReport)orType.Value);
    }
    if (orType.Value?.GetType() == typeof(RelatedUnchangedDocumentDiagnosticReport))
    {
    return new DocumentDiagnosticReport((RelatedUnchangedDocumentDiagnosticReport)orType.Value);
    }
    }
    throw new JsonSerializationException($"Unexpected token type.");
    }
    public override void WriteJson(JsonWriter writer, DocumentDiagnosticReport? value, JsonSerializer serializer)
    {
    _orType.WriteJson(writer, value, serializer);
    }
    }
}
