// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Registration options for a <see cref="DocumentRangeFormattingRequest" />.
    /// </summary>
    [DataContract]
    public record DocumentRangeFormattingRegistrationOptions
    {
        [JsonConstructor]
        public DocumentRangeFormattingRegistrationOptions(
            DocumentSelector? documentSelector = null,
            bool? rangesSupport = null,
            bool? workDoneProgress = null
        )
        {
            DocumentSelector = documentSelector;
            RangesSupport = rangesSupport;
            WorkDoneProgress = workDoneProgress;
        }
        /// <summary>
        /// A document selector to identify the scope of the registration. If set to null
        /// the document selector provided on the client side will be used.
        /// </summary>
        [JsonConverter(typeof(DocumentSelectorConverter))]
        [DataMember(Name = "documentSelector")]
        public DocumentSelector? DocumentSelector { get; init; }
        /// <summary>
        /// Whether the server supports formatting multiple ranges at once.
        /// 
        /// </summary>
        [Proposed]
        [Since("3.18.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "rangesSupport")]
        public bool? RangesSupport { get; init; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
    }

}
