// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Registration options for a <see cref="DocumentOnTypeFormattingRequest" />.
    /// </summary>
    [DataContract]
    public record DocumentOnTypeFormattingRegistrationOptions
    {
        [JsonConstructor]
        public DocumentOnTypeFormattingRegistrationOptions(
            string firstTriggerCharacter,
            DocumentSelector? documentSelector = null,
            ImmutableArray<string> moreTriggerCharacter = default!
        )
        {
            DocumentSelector = documentSelector;
            FirstTriggerCharacter = firstTriggerCharacter;
            MoreTriggerCharacter = moreTriggerCharacter;
        }
        /// <summary>
        /// A document selector to identify the scope of the registration. If set to null
        /// the document selector provided on the client side will be used.
        /// </summary>
        [JsonConverter(typeof(DocumentSelectorConverter))]
        [DataMember(Name = "documentSelector")]
        public DocumentSelector? DocumentSelector { get; init; }
        /// <summary>
        /// A character on which formatting should be triggered, like `{`.
        /// </summary>
        [DataMember(Name = "firstTriggerCharacter")]
        public string FirstTriggerCharacter { get; init; }
        /// <summary>
        /// More trigger characters.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<string>))]
        [DataMember(Name = "moreTriggerCharacter")]
        public ImmutableArray<string> MoreTriggerCharacter { get; init; }
    }

}
