// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Provider options for a <see cref="DocumentRangeFormattingRequest" />.
    /// </summary>
    [DataContract]
    public record DocumentRangeFormattingOptions
    {
        [JsonConstructor]
        public DocumentRangeFormattingOptions(
            bool? rangesSupport = null,
            bool? workDoneProgress = null
        )
        {
            RangesSupport = rangesSupport;
            WorkDoneProgress = workDoneProgress;
        }
        /// <summary>
        /// Whether the server supports formatting multiple ranges at once.
        /// 
        /// </summary>
        [Proposed]
        [Since("3.18.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "rangesSupport")]
        public bool? RangesSupport { get; init; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
    }

}
