// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The document diagnostic report kinds.
    /// 
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DocumentDiagnosticReportKind
    {
        /// <summary>
        /// A diagnostic report with a full
        /// set of problems.
        /// </summary>
        [EnumMember(Value = "full")]Full,

        /// <summary>
        /// A report indicating that the last
        /// returned report is still accurate.
        /// </summary>
        [EnumMember(Value = "unchanged")]Unchanged,

    }
}
