// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The client capabilities of a <see cref="DocumentLinkRequest" />.
    /// </summary>
    [DataContract]
    public record DocumentLinkClientCapabilities
    {
        [JsonConstructor]
        public DocumentLinkClientCapabilities(
            bool? dynamicRegistration = null,
            bool? tooltipSupport = null
        )
        {
            DynamicRegistration = dynamicRegistration;
            TooltipSupport = tooltipSupport;
        }
        /// <summary>
        /// Whether document link supports dynamic registration.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "dynamicRegistration")]
        public bool? DynamicRegistration { get; init; }
        /// <summary>
        /// Whether the client supports the `tooltip` property on `DocumentLink`.
        /// 
        /// </summary>
        [Since("3.15.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "tooltipSupport")]
        public bool? TooltipSupport { get; init; }
    }

}
