// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;

namespace Microsoft.LanguageServer.Protocol {
    public class DocumentFilterConverter : JsonConverter<DocumentFilter>
    {
    private OrTypeConverter<TextDocumentFilter,NotebookCellTextDocumentFilter> _orType;
    public DocumentFilterConverter()
    {
    _orType = new OrTypeConverter<TextDocumentFilter,NotebookCellTextDocumentFilter>();
    }
    public override DocumentFilter? ReadJson(JsonReader reader, Type objectType, DocumentFilter? existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
    reader = reader ?? throw new ArgumentNullException(nameof(reader));
    if (reader.TokenType == JsonToken.Null) { return null; }
    var o = _orType.ReadJson(reader, objectType, existingValue, serializer);
    if (o is OrType<TextDocumentFilter,NotebookCellTextDocumentFilter> orType)
    {
    if (orType.Value?.GetType() == typeof(TextDocumentFilter))
    {
    return new DocumentFilter((TextDocumentFilter)orType.Value);
    }
    if (orType.Value?.GetType() == typeof(NotebookCellTextDocumentFilter))
    {
    return new DocumentFilter((NotebookCellTextDocumentFilter)orType.Value);
    }
    }
    throw new JsonSerializationException($"Unexpected token type.");
    }
    public override void WriteJson(JsonWriter writer, DocumentFilter? value, JsonSerializer serializer)
    {
    _orType.WriteJson(writer, value, serializer);
    }
    }
}
