// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Registration options for a <see cref="ExecuteCommandRequest" />.
    /// </summary>
    [DataContract]
    public record ExecuteCommandRegistrationOptions
    {
        [JsonConstructor]
        public ExecuteCommandRegistrationOptions(
            ImmutableArray<string> commands,
            bool? workDoneProgress = null
        )
        {
            Commands = commands;
            WorkDoneProgress = workDoneProgress;
        }
        /// <summary>
        /// The commands to be executed on the server
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<string>))]
        [DataMember(Name = "commands")]
        public ImmutableArray<string> Commands { get; init; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
    }

}
