// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record ExecutionSummary
    {
        [JsonConstructor]
        public ExecutionSummary(
            long executionOrder,
            bool? success = null
        )
        {
            ExecutionOrder = executionOrder;
            Success = success;
        }
        /// <summary>
        /// A strict monotonically increasing value
        /// indicating the execution order of a cell
        /// inside a notebook.
        /// </summary>
        [DataMember(Name = "executionOrder")]
        public long ExecutionOrder { get => executionOrder; set => executionOrder = Validators.validUInteger(value); }
        private long executionOrder;
        /// <summary>
        /// Whether the execution was successful or
        /// not if known by the client.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "success")]
        public bool? Success { get; init; }
    }

}
