// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Represents information on a file/folder delete.
    /// 
    /// </summary>
    [Since("3.16.0")]
    [DataContract]
    public record FileDelete
    {
        [JsonConstructor]
        public FileDelete(
            string uri
        )
        {
            Uri = uri;
        }
        /// <summary>
        /// A file:// URI for the location of the file/folder being deleted.
        /// </summary>
        [DataMember(Name = "uri")]
        public string Uri { get; init; }
    }

}
