// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Options for notifications/requests for user operations on files.
    /// 
    /// </summary>
    [Since("3.16.0")]
    [DataContract]
    public record FileOperationOptions
    {
        [JsonConstructor]
        public FileOperationOptions(
            FileOperationRegistrationOptions? didCreate = null,
            FileOperationRegistrationOptions? willCreate = null,
            FileOperationRegistrationOptions? didRename = null,
            FileOperationRegistrationOptions? willRename = null,
            FileOperationRegistrationOptions? didDelete = null,
            FileOperationRegistrationOptions? willDelete = null
        )
        {
            DidCreate = didCreate;
            WillCreate = willCreate;
            DidRename = didRename;
            WillRename = willRename;
            DidDelete = didDelete;
            WillDelete = willDelete;
        }
        /// <summary>
        /// The server is interested in receiving didCreateFiles notifications.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "didCreate")]
        public FileOperationRegistrationOptions? DidCreate { get; init; }
        /// <summary>
        /// The server is interested in receiving willCreateFiles requests.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "willCreate")]
        public FileOperationRegistrationOptions? WillCreate { get; init; }
        /// <summary>
        /// The server is interested in receiving didRenameFiles notifications.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "didRename")]
        public FileOperationRegistrationOptions? DidRename { get; init; }
        /// <summary>
        /// The server is interested in receiving willRenameFiles requests.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "willRename")]
        public FileOperationRegistrationOptions? WillRename { get; init; }
        /// <summary>
        /// The server is interested in receiving didDeleteFiles file notifications.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "didDelete")]
        public FileOperationRegistrationOptions? DidDelete { get; init; }
        /// <summary>
        /// The server is interested in receiving willDeleteFiles file requests.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "willDelete")]
        public FileOperationRegistrationOptions? WillDelete { get; init; }
    }

}
