// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The options to register for file operations.
    /// 
    /// </summary>
    [Since("3.16.0")]
    [DataContract]
    public record FileOperationRegistrationOptions
    {
        [JsonConstructor]
        public FileOperationRegistrationOptions(
            ImmutableArray<FileOperationFilter> filters
        )
        {
            Filters = filters;
        }
        /// <summary>
        /// The actual filters.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<FileOperationFilter>))]
        [DataMember(Name = "filters")]
        public ImmutableArray<FileOperationFilter> Filters { get; init; }
    }

}
