// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record FoldingRangeRegistrationOptions
    {
        [JsonConstructor]
        public FoldingRangeRegistrationOptions(
            DocumentSelector? documentSelector = null,
            bool? workDoneProgress = null,
            string? id = null
        )
        {
            DocumentSelector = documentSelector;
            WorkDoneProgress = workDoneProgress;
            Id = id;
        }
        /// <summary>
        /// A document selector to identify the scope of the registration. If set to null
        /// the document selector provided on the client side will be used.
        /// </summary>
        [JsonConverter(typeof(DocumentSelectorConverter))]
        [DataMember(Name = "documentSelector")]
        public DocumentSelector? DocumentSelector { get; init; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
        /// <summary>
        /// The id used to register the request. The id can be used to deregister
        /// the request again. See also Registration#id.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "id")]
        public string? Id { get; init; }
    }

}
