// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;

namespace Microsoft.LanguageServer.Protocol {
    public class GlobPatternConverter : JsonConverter<GlobPattern>
    {
    private OrTypeConverter<Pattern,RelativePattern> _orType;
    public GlobPatternConverter()
    {
    _orType = new OrTypeConverter<Pattern,RelativePattern>();
    }
    public override GlobPattern? ReadJson(JsonReader reader, Type objectType, GlobPattern? existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
    reader = reader ?? throw new ArgumentNullException(nameof(reader));
    if (reader.TokenType == JsonToken.Null) { return null; }
    var o = _orType.ReadJson(reader, objectType, existingValue, serializer);
    if (o is OrType<Pattern,RelativePattern> orType)
    {
    if (orType.Value?.GetType() == typeof(Pattern))
    {
    return new GlobPattern((Pattern)orType.Value);
    }
    if (orType.Value?.GetType() == typeof(RelativePattern))
    {
    return new GlobPattern((RelativePattern)orType.Value);
    }
    }
    throw new JsonSerializationException($"Unexpected token type.");
    }
    public override void WriteJson(JsonWriter writer, GlobPattern? value, JsonSerializer serializer)
    {
    _orType.WriteJson(writer, value, serializer);
    }
    }
}
