// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The result of a hover request.
    /// </summary>
    [DataContract]
    public record Hover
    {
        [JsonConstructor]
        public Hover(
            OrType<MarkupContent, MarkedString, ImmutableArray<MarkedString>> contents,
            Range? range = null
        )
        {
            Contents = contents;
            Range = range;
        }
        /// <summary>
        /// The hover's content
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<MarkupContent, MarkedString, ImmutableArray<MarkedString>>))]
        [DataMember(Name = "contents")]
        public OrType<MarkupContent, MarkedString, ImmutableArray<MarkedString>> Contents { get; init; }
        /// <summary>
        /// An optional range inside the text document that is used to
        /// visualize the hover, e.g. by changing the background color.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "range")]
        public Range? Range { get; init; }
    }

}
