// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record HoverClientCapabilities
    {
        [JsonConstructor]
        public HoverClientCapabilities(
            bool? dynamicRegistration = null,
            ImmutableArray<MarkupKind> contentFormat = default!
        )
        {
            DynamicRegistration = dynamicRegistration;
            ContentFormat = contentFormat;
        }
        /// <summary>
        /// Whether hover supports dynamic registration.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "dynamicRegistration")]
        public bool? DynamicRegistration { get; init; }
        /// <summary>
        /// Client supports the following content formats for the content
        /// property. The order describes the preferred format of the client.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<MarkupKind>))]
        [DataMember(Name = "contentFormat")]
        public ImmutableArray<MarkupKind> ContentFormat { get; init; }
    }

}
