// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The result returned from an initialize request.
    /// </summary>
    [DataContract]
    public record InitializeResult
    {
        [JsonConstructor]
        public InitializeResult(
            ServerCapabilities capabilities,
            ServerInfo? serverInfo = null
        )
        {
            Capabilities = capabilities;
            ServerInfo = serverInfo;
        }
        /// <summary>
        /// The capabilities the language server provides.
        /// </summary>
        [DataMember(Name = "capabilities")]
        public ServerCapabilities Capabilities { get; init; }
        /// <summary>
        /// Information about the server.
        /// 
        /// </summary>
        [Since("3.15.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "serverInfo")]
        public ServerInfo? ServerInfo { get; init; }
    }

}
