// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Inlay hint client capabilities.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record InlayHintClientCapabilities
    {
        [JsonConstructor]
        public InlayHintClientCapabilities(
            bool? dynamicRegistration = null,
            ClientInlayHintResolveOptions? resolveSupport = null
        )
        {
            DynamicRegistration = dynamicRegistration;
            ResolveSupport = resolveSupport;
        }
        /// <summary>
        /// Whether inlay hints support dynamic registration.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "dynamicRegistration")]
        public bool? DynamicRegistration { get; init; }
        /// <summary>
        /// Indicates which properties a client can resolve lazily on an inlay
        /// hint.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "resolveSupport")]
        public ClientInlayHintResolveOptions? ResolveSupport { get; init; }
    }

}
