// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A parameter literal used in inlay hint requests.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record InlayHintParams
    {
        [JsonConstructor]
        public InlayHintParams(
            TextDocumentIdentifier textDocument,
            Range range,
            ProgressToken? workDoneToken = null
        )
        {
            TextDocument = textDocument;
            Range = range;
            WorkDoneToken = workDoneToken;
        }
        /// <summary>
        /// The text document.
        /// </summary>
        [DataMember(Name = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; init; }
        /// <summary>
        /// The document range for which inlay hints should be computed.
        /// </summary>
        [DataMember(Name = "range")]
        public Range Range { get; init; }
        /// <summary>
        /// An optional token that a server can use to report work done progress.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneToken")]
        public ProgressToken? WorkDoneToken { get; init; }
    }

}
