// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// An inlay hint label part allows for interactive and composite labels
    /// of inlay hints.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record InlayHintLabelPart
    {
        [JsonConstructor]
        public InlayHintLabelPart(
            string value,
            OrType<string, MarkupContent>? tooltip = null,
            Location? location = null,
            CommandAction? command = null
        )
        {
            Value = value;
            Tooltip = tooltip;
            Location = location;
            Command = command;
        }
        /// <summary>
        /// The value of this label part.
        /// </summary>
        [DataMember(Name = "value")]
        public string Value { get; init; }
        /// <summary>
        /// The tooltip text when you hover over this label part. Depending on
        /// the client capability `inlayHint.resolveSupport` clients might resolve
        /// this property late using the resolve request.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, MarkupContent>))]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "tooltip")]
        public OrType<string, MarkupContent>? Tooltip { get; init; }
        /// <summary>
        /// An optional source code location that represents this
        /// label part.
        /// 
        /// The editor will use this location for the hover and for code navigation
        /// features: This part will become a clickable link that resolves to the
        /// definition of the symbol at the given location (not necessarily the
        /// location itself), it shows the hover that shows at the given location,
        /// and it shows a context menu with further code navigation commands.
        /// 
        /// Depending on the client capability `inlayHint.resolveSupport` clients
        /// might resolve this property late using the resolve request.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "location")]
        public Location? Location { get; init; }
        /// <summary>
        /// An optional command for this label part.
        /// 
        /// Depending on the client capability `inlayHint.resolveSupport` clients
        /// might resolve this property late using the resolve request.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "command")]
        public CommandAction? Command { get; init; }
    }

}
