// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Provide an inline value through an expression evaluation.
    /// If only a range is specified, the expression will be extracted from the underlying document.
    /// An optional expression can be used to override the extracted expression.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record InlineValueEvaluatableExpression
    {
        [JsonConstructor]
        public InlineValueEvaluatableExpression(
            Range range,
            string? expression = null
        )
        {
            Range = range;
            Expression = expression;
        }
        /// <summary>
        /// The document range for which the inline value applies.
        /// The range is used to extract the evaluatable expression from the underlying document.
        /// </summary>
        [DataMember(Name = "range")]
        public Range Range { get; init; }
        /// <summary>
        /// If specified the expression overrides the extracted expression.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "expression")]
        public string? Expression { get; init; }
    }

}
