// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Inline value information can be provided by different means:
    /// - directly as a text value (class InlineValueText).
    /// - as a name to use for a variable lookup (class InlineValueVariableLookup)
    /// - as an evaluatable expression (class InlineValueEvaluatableExpression)
    /// The InlineValue types combines all inline value types into one type.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [JsonConverter(typeof(InlineValueConverter))]
    [DataContract]
    public record InlineValue: OrType<InlineValueText, InlineValueVariableLookup, InlineValueEvaluatableExpression>
    {
        public InlineValue(InlineValueText InlineValueText): base(InlineValueText) {}
        public InlineValue(InlineValueVariableLookup InlineValueVariableLookup): base(InlineValueVariableLookup) {}
        public InlineValue(InlineValueEvaluatableExpression InlineValueEvaluatableExpression): base(InlineValueEvaluatableExpression) {}
    }

}
