// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Provide inline value as text.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record InlineValueText
    {
        [JsonConstructor]
        public InlineValueText(
            Range range,
            string text
        )
        {
            Range = range;
            Text = text;
        }
        /// <summary>
        /// The document range for which the inline value applies.
        /// </summary>
        [DataMember(Name = "range")]
        public Range Range { get; init; }
        /// <summary>
        /// The text of the inline value.
        /// </summary>
        [DataMember(Name = "text")]
        public string Text { get; init; }
    }

}
