// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT


namespace Microsoft.LanguageServer.Protocol {
    public interface IRequest<TParams> : IMessage
    {

        OrType<string, int> Id { get; }

        string Method { get; }

        TParams Params { get; }
    }
}
