// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Represents a location inside a resource, such as a line
    /// inside a text file.
    /// </summary>
    [DataContract]
    public record Location
    {
        [JsonConstructor]
        public Location(
            Uri uri,
            Range range
        )
        {
            Uri = uri;
            Range = range;
        }
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "uri")]
        public Uri Uri { get; init; }
        [DataMember(Name = "range")]
        public Range Range { get; init; }
    }

}
