// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The log message parameters.
    /// </summary>
    [DataContract]
    public record LogMessageParams
    {
        [JsonConstructor]
        public LogMessageParams(
            MessageType type,
            string message
        )
        {
            Type = type;
            Message = message;
        }
        /// <summary>
        /// The message type. See <see cref="MessageType" />
        /// </summary>
        [DataMember(Name = "type")]
        public MessageType Type { get; init; }
        /// <summary>
        /// The actual message.
        /// </summary>
        [DataMember(Name = "message")]
        public string Message { get; init; }
    }

}
