// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT


namespace Microsoft.LanguageServer.Protocol {
    using System;

    [AttributeUsage(AttributeTargets.Class)]
    public class LSPResponseAttribute : Attribute
    {
        public LSPResponseAttribute(Type request)
        {
            Request = request;
        }


        public Type Request { get; }
    }
}
