// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// MarkedString can be used to render human readable text. It is either a markdown string
    /// or a code-block that provides a language and a code snippet. The language identifier
    /// is semantically equal to the optional language identifier in fenced code blocks in GitHub
    /// issues. See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
    /// 
    /// The pair of a language and a value is an equivalent to markdown:
    /// ```${language}
    /// ${value}
    /// ```
    /// 
    /// Note that markdown strings will be sanitized - that means html will be escaped.
    /// </summary>
    [Obsolete("use MarkupContent instead.")]
    [JsonConverter(typeof(MarkedStringConverter))]
    [DataContract]
    public record MarkedString: OrType<string, MarkedStringWithLanguage>
    {
        public MarkedString(string stringValue): base(stringValue) {}
        public MarkedString(MarkedStringWithLanguage MarkedStringWithLanguage): base(MarkedStringWithLanguage) {}
    }

}
