// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;

namespace Microsoft.LanguageServer.Protocol {
    public class MarkedStringConverter : JsonConverter<MarkedString>
    {
    private OrTypeConverter<string,MarkedStringWithLanguage> _orType;
    public MarkedStringConverter()
    {
    _orType = new OrTypeConverter<string,MarkedStringWithLanguage>();
    }
    public override MarkedString? ReadJson(JsonReader reader, Type objectType, MarkedString? existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
    reader = reader ?? throw new ArgumentNullException(nameof(reader));
    if (reader.TokenType == JsonToken.Null) { return null; }
    var o = _orType.ReadJson(reader, objectType, existingValue, serializer);
    if (o is OrType<string,MarkedStringWithLanguage> orType)
    {
    if (orType.Value?.GetType() == typeof(string))
    {
    return new MarkedString((string)orType.Value);
    }
    if (orType.Value?.GetType() == typeof(MarkedStringWithLanguage))
    {
    return new MarkedString((MarkedStringWithLanguage)orType.Value);
    }
    }
    throw new JsonSerializationException($"Unexpected token type.");
    }
    public override void WriteJson(JsonWriter writer, MarkedString? value, JsonSerializer serializer)
    {
    _orType.WriteJson(writer, value, serializer);
    }
    }
}
