// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Moniker definition to match LSIF 0.5 moniker definition.
    /// 
    /// </summary>
    [Since("3.16.0")]
    [DataContract]
    public record Moniker
    {
        [JsonConstructor]
        public Moniker(
            string scheme,
            string identifier,
            UniquenessLevel unique,
            MonikerKind? kind = null
        )
        {
            Scheme = scheme;
            Identifier = identifier;
            Unique = unique;
            Kind = kind;
        }
        /// <summary>
        /// The scheme of the moniker. For example tsc or .Net
        /// </summary>
        [DataMember(Name = "scheme")]
        public string Scheme { get; init; }
        /// <summary>
        /// The identifier of the moniker. The value is opaque in LSIF however
        /// schema owners are allowed to define the structure if they want.
        /// </summary>
        [DataMember(Name = "identifier")]
        public string Identifier { get; init; }
        /// <summary>
        /// The scope in which the moniker is unique
        /// </summary>
        [DataMember(Name = "unique")]
        public UniquenessLevel Unique { get; init; }
        /// <summary>
        /// The moniker kind if known.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "kind")]
        public MonikerKind? Kind { get; init; }
    }

}
