// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A literal to identify a notebook document in the client.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record NotebookDocumentIdentifier
    {
        [JsonConstructor]
        public NotebookDocumentIdentifier(
            Uri uri
        )
        {
            Uri = uri;
        }
        /// <summary>
        /// The notebook document's uri.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "uri")]
        public Uri Uri { get; init; }
    }

}
