// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record NotebookCellLanguage
    {
        [JsonConstructor]
        public NotebookCellLanguage(
            string language
        )
        {
            Language = language;
        }
        [DataMember(Name = "language")]
        public string Language { get; init; }
    }

}
