// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A notification sent when a notebook closes.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [Direction(MessageDirection.ServerToClient)]
    [DataContract]
    public record NotebookDocumentDidCloseNotification: INotification<DidCloseNotebookDocumentParams>
    {
        [JsonConstructor]
        public NotebookDocumentDidCloseNotification(
            string method,
            DidCloseNotebookDocumentParams paramsValue,
            string jsonrpc = "2.0"
        )
        {
            JsonRPC = jsonrpc;
            Method = method;
            Params = paramsValue;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Notification method.
        /// </summary>
        [DataMember(Name = "method")]
        public string Method { get; init; }
        /// <summary>
        /// The Notification parameters.
        /// </summary>
        [DataMember(Name = "params")]
        public DidCloseNotebookDocumentParams Params { get; init; }
    }

}
