// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A change event for a notebook document.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record NotebookDocumentChangeEvent
    {
        [JsonConstructor]
        public NotebookDocumentChangeEvent(
            LSPObject? metadata = null,
            NotebookDocumentCellChanges? cells = null
        )
        {
            Metadata = metadata;
            Cells = cells;
        }
        /// <summary>
        /// The changed meta data if any.
        /// 
        /// Note: should always be an object literal (e.g. LSPObject)
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "metadata")]
        public LSPObject? Metadata { get; init; }
        /// <summary>
        /// Changes to cells
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "cells")]
        public NotebookDocumentCellChanges? Cells { get; init; }
    }

}
