// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A notebook document filter denotes a notebook document by
    /// different properties. The properties will be match
    /// against the notebook's URI (same as with documents)
    /// 
    /// </summary>
    [Since("3.17.0")]
    [JsonConverter(typeof(NotebookDocumentFilterConverter))]
    [DataContract]
    public record NotebookDocumentFilter: OrType<NotebookDocumentFilterNotebookType, NotebookDocumentFilterScheme, NotebookDocumentFilterPattern>
    {
        public NotebookDocumentFilter(NotebookDocumentFilterNotebookType NotebookDocumentFilterNotebookType): base(NotebookDocumentFilterNotebookType) {}
        public NotebookDocumentFilter(NotebookDocumentFilterScheme NotebookDocumentFilterScheme): base(NotebookDocumentFilterScheme) {}
        public NotebookDocumentFilter(NotebookDocumentFilterPattern NotebookDocumentFilterPattern): base(NotebookDocumentFilterPattern) {}
    }

}
