// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A notebook document.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record NotebookDocument
    {
        [JsonConstructor]
        public NotebookDocument(
            Uri uri,
            string notebookType,
            int version,
            ImmutableArray<NotebookCell> cells,
            LSPObject? metadata = null
        )
        {
            Uri = uri;
            NotebookType = notebookType;
            Version = version;
            Metadata = metadata;
            Cells = cells;
        }
        /// <summary>
        /// The notebook document's uri.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "uri")]
        public Uri Uri { get; init; }
        /// <summary>
        /// The type of the notebook.
        /// </summary>
        [DataMember(Name = "notebookType")]
        public string NotebookType { get; init; }
        /// <summary>
        /// The version number of this document (it will increase after each
        /// change, including undo/redo).
        /// </summary>
        [DataMember(Name = "version")]
        public int Version { get; init; }
        /// <summary>
        /// Additional metadata stored with the notebook
        /// document.
        /// 
        /// Note: should always be an object literal (e.g. LSPObject)
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "metadata")]
        public LSPObject? Metadata { get; init; }
        /// <summary>
        /// The cells of a notebook.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<NotebookCell>))]
        [DataMember(Name = "cells")]
        public ImmutableArray<NotebookCell> Cells { get; init; }
    }

}
