// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Notebook specific client capabilities.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record NotebookDocumentSyncClientCapabilities
    {
        [JsonConstructor]
        public NotebookDocumentSyncClientCapabilities(
            bool? dynamicRegistration = null,
            bool? executionSummarySupport = null
        )
        {
            DynamicRegistration = dynamicRegistration;
            ExecutionSummarySupport = executionSummarySupport;
        }
        /// <summary>
        /// Whether implementation supports dynamic registration. If this is
        /// set to `true` the client supports the new
        /// `(TextDocumentRegistrationOptions & StaticRegistrationOptions)`
        /// return value for the corresponding server capability as well.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "dynamicRegistration")]
        public bool? DynamicRegistration { get; init; }
        /// <summary>
        /// The client supports sending execution summary data per cell.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "executionSummarySupport")]
        public bool? ExecutionSummarySupport { get; init; }
    }

}
