// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record PrepareRenamePlaceholder
    {
        [JsonConstructor]
        public PrepareRenamePlaceholder(
            Range range,
            string placeholder
        )
        {
            Range = range;
            Placeholder = placeholder;
        }
        [DataMember(Name = "range")]
        public Range Range { get; init; }
        [DataMember(Name = "placeholder")]
        public string Placeholder { get; init; }
    }

}
