// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The publish diagnostic notification's parameters.
    /// </summary>
    [DataContract]
    public record PublishDiagnosticsParams
    {
        [JsonConstructor]
        public PublishDiagnosticsParams(
            Uri uri,
            ImmutableArray<Diagnostic> diagnostics,
            int? version = null
        )
        {
            Uri = uri;
            Version = version;
            Diagnostics = diagnostics;
        }
        /// <summary>
        /// The URI for which diagnostic information is reported.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "uri")]
        public Uri Uri { get; init; }
        /// <summary>
        /// Optional the version number of the document the diagnostics are published for.
        /// 
        /// </summary>
        [Since("3.15.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "version")]
        public int? Version { get; init; }
        /// <summary>
        /// An array of diagnostic information items.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<Diagnostic>))]
        [DataMember(Name = "diagnostics")]
        public ImmutableArray<Diagnostic> Diagnostics { get; init; }
    }

}
