// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A range in a text document expressed as (zero-based) start and end positions.
    /// 
    /// If you want to specify a range that contains a line including the line ending
    /// character(s) then use an end position denoting the start of the next line.
    /// For example:
    /// ```ts
    /// {
    ///     start: { line: 5, character: 23 }
    ///     end : { line 6, character : 0 }
    /// }
    /// ```
    /// </summary>
    [DataContract]
    public record Range
    {
        [JsonConstructor]
        public Range(
            Position start,
            Position end
        )
        {
            Start = start;
            End = end;
        }
        /// <summary>
        /// The range's start position.
        /// </summary>
        [DataMember(Name = "start")]
        public Position Start { get; init; }
        /// <summary>
        /// The range's end position.
        /// </summary>
        [DataMember(Name = "end")]
        public Position End { get; init; }
    }

}
