// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Value-object that contains additional information when
    /// requesting references.
    /// </summary>
    [DataContract]
    public record ReferenceContext
    {
        [JsonConstructor]
        public ReferenceContext(
            bool includeDeclaration
        )
        {
            IncludeDeclaration = includeDeclaration;
        }
        /// <summary>
        /// Include the declaration of the current symbol.
        /// </summary>
        [DataMember(Name = "includeDeclaration")]
        public bool IncludeDeclaration { get; init; }
    }

}
