// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Client capabilities specific to regular expressions.
    /// 
    /// </summary>
    [Since("3.16.0")]
    [DataContract]
    public record RegularExpressionsClientCapabilities
    {
        [JsonConstructor]
        public RegularExpressionsClientCapabilities(
            RegularExpressionEngineKind engine,
            string? version = null
        )
        {
            Engine = engine;
            Version = version;
        }
        /// <summary>
        /// The engine's name.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<RegularExpressionEngineKind>))]
        [DataMember(Name = "engine")]
        public RegularExpressionEngineKind Engine { get; init; }
        /// <summary>
        /// The engine's version.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "version")]
        public string? Version { get; init; }
    }

}
