// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// An unchanged diagnostic report with a set of related documents.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record RelatedUnchangedDocumentDiagnosticReport
    {
        [JsonConstructor]
        public RelatedUnchangedDocumentDiagnosticReport(
            string kind,
            string resultId,
            ImmutableDictionary<Uri, RelatedUnchangedDocumentDiagnosticReportRelatedDocumentsValue> relatedDocuments = default!
        )
        {
            RelatedDocuments = relatedDocuments;
            Kind = kind;
            ResultId = resultId;
        }
        /// <summary>
        /// Diagnostics of related documents. This information is useful
        /// in programming languages where code in a file A can generate
        /// diagnostics in a file B which A depends on. An example of
        /// such a language is C/C++ where marco definitions in a file
        /// a.cpp and result in errors in a header file b.hpp.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [DataMember(Name = "relatedDocuments")]
        public ImmutableDictionary<Uri, RelatedUnchangedDocumentDiagnosticReportRelatedDocumentsValue> RelatedDocuments { get; init; }
        /// <summary>
        /// A document diagnostic report indicating
        /// no changes to the last result. A server can
        /// only return `unchanged` if result ids are
        /// provided.
        /// </summary>
        [DataMember(Name = "kind")]
        public string Kind { get; init; } = "unchanged";
        /// <summary>
        /// A result id which will be sent on the next
        /// diagnostic request for the same document.
        /// </summary>
        [DataMember(Name = "resultId")]
        public string ResultId { get; init; }
    }

}
