// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Registration options for a <see cref="RenameRequest" />.
    /// </summary>
    [DataContract]
    public record RenameRegistrationOptions
    {
        [JsonConstructor]
        public RenameRegistrationOptions(
            DocumentSelector? documentSelector = null,
            bool? prepareProvider = null,
            bool? workDoneProgress = null
        )
        {
            DocumentSelector = documentSelector;
            PrepareProvider = prepareProvider;
            WorkDoneProgress = workDoneProgress;
        }
        /// <summary>
        /// A document selector to identify the scope of the registration. If set to null
        /// the document selector provided on the client side will be used.
        /// </summary>
        [JsonConverter(typeof(DocumentSelectorConverter))]
        [DataMember(Name = "documentSelector")]
        public DocumentSelector? DocumentSelector { get; init; }
        /// <summary>
        /// Renames should be checked and tested before being executed.
        /// 
        /// </summary>
        [Since("version 3.12.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "prepareProvider")]
        public bool? PrepareProvider { get; init; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
    }

}
