// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Rename file operation
    /// </summary>
    [DataContract]
    public record RenameFile
    {
        [JsonConstructor]
        public RenameFile(
            string kind,
            Uri oldUri,
            Uri newUri,
            RenameFileOptions? options = null,
            ChangeAnnotationIdentifier? annotationId = null
        )
        {
            Kind = kind;
            OldUri = oldUri;
            NewUri = newUri;
            Options = options;
            AnnotationId = annotationId;
        }
        /// <summary>
        /// A rename
        /// </summary>
        [DataMember(Name = "kind")]
        public string Kind { get; init; } = "rename";
        /// <summary>
        /// The old (existing) location.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "oldUri")]
        public Uri OldUri { get; init; }
        /// <summary>
        /// The new location.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "newUri")]
        public Uri NewUri { get; init; }
        /// <summary>
        /// Rename options.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "options")]
        public RenameFileOptions? Options { get; init; }
        /// <summary>
        /// An optional annotation identifier describing the operation.
        /// 
        /// </summary>
        [Since("3.16.0")]
        [JsonConverter(typeof(CustomStringConverter<ChangeAnnotationIdentifier>))]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "annotationId")]
        public ChangeAnnotationIdentifier? AnnotationId { get; init; }
    }

}
