// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The parameters sent in notifications/requests for user-initiated renames of
    /// files.
    /// 
    /// </summary>
    [Since("3.16.0")]
    [DataContract]
    public record RenameFilesParams
    {
        [JsonConstructor]
        public RenameFilesParams(
            ImmutableArray<FileRename> files
        )
        {
            Files = files;
        }
        /// <summary>
        /// An array of all files/folders renamed in this operation. When a folder is renamed, only
        /// the folder will be included, and not its children.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<FileRename>))]
        [DataMember(Name = "files")]
        public ImmutableArray<FileRename> Files { get; init; }
    }

}
