// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Save options.
    /// </summary>
    [DataContract]
    public record SaveOptions
    {
        [JsonConstructor]
        public SaveOptions(
            bool? includeText = null
        )
        {
            IncludeText = includeText;
        }
        /// <summary>
        /// The client is supposed to include the content on save.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "includeText")]
        public bool? IncludeText { get; init; }
    }

}
