// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Since("3.16.0")]
    [DataContract]
    public record SemanticTokensDeltaPartialResult
    {
        [JsonConstructor]
        public SemanticTokensDeltaPartialResult(
            ImmutableArray<SemanticTokensEdit> edits
        )
        {
            Edits = edits;
        }
        [JsonConverter(typeof(CustomArrayConverter<SemanticTokensEdit>))]
        [DataMember(Name = "edits")]
        public ImmutableArray<SemanticTokensEdit> Edits { get; init; }
    }

}
