// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record SetTraceParams
    {
        [JsonConstructor]
        public SetTraceParams(
            TraceValue value
        )
        {
            Value = value;
        }
        [DataMember(Name = "value")]
        public TraceValue Value { get; init; }
    }

}
