// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Show message request client capabilities
    /// </summary>
    [DataContract]
    public record ShowMessageRequestClientCapabilities
    {
        [JsonConstructor]
        public ShowMessageRequestClientCapabilities(
            ClientShowMessageActionItemOptions? messageActionItem = null
        )
        {
            MessageActionItem = messageActionItem;
        }
        /// <summary>
        /// Capabilities specific to the `MessageActionItem` type.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "messageActionItem")]
        public ClientShowMessageActionItemOptions? MessageActionItem { get; init; }
    }

}
