// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Additional information about the context in which a signature help request was triggered.
    /// 
    /// </summary>
    [Since("3.15.0")]
    [DataContract]
    public record SignatureHelpContext
    {
        [JsonConstructor]
        public SignatureHelpContext(
            SignatureHelpTriggerKind triggerKind,
            bool isRetrigger,
            string? triggerCharacter = null,
            SignatureHelp? activeSignatureHelp = null
        )
        {
            TriggerKind = triggerKind;
            TriggerCharacter = triggerCharacter;
            IsRetrigger = isRetrigger;
            ActiveSignatureHelp = activeSignatureHelp;
        }
        /// <summary>
        /// Action that caused signature help to be triggered.
        /// </summary>
        [DataMember(Name = "triggerKind")]
        public SignatureHelpTriggerKind TriggerKind { get; init; }
        /// <summary>
        /// Character that caused signature help to be triggered.
        /// 
        /// This is undefined when `triggerKind !== SignatureHelpTriggerKind.TriggerCharacter`
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "triggerCharacter")]
        public string? TriggerCharacter { get; init; }
        /// <summary>
        /// `true` if signature help was already showing when it was triggered.
        /// 
        /// Retriggers occurs when the signature help is already active and can be caused by actions such as
        /// typing a trigger character, a cursor move, or document content changes.
        /// </summary>
        [DataMember(Name = "isRetrigger")]
        public bool IsRetrigger { get; init; }
        /// <summary>
        /// The currently active `SignatureHelp`.
        /// 
        /// The `activeSignatureHelp` has its `SignatureHelp.activeSignature` field updated based on
        /// the user navigating through available signatures.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "activeSignatureHelp")]
        public SignatureHelp? ActiveSignatureHelp { get; init; }
    }

}
