// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Parameters for a <see cref="SignatureHelpRequest" />.
    /// </summary>
    [DataContract]
    public record SignatureHelpParams
    {
        [JsonConstructor]
        public SignatureHelpParams(
            TextDocumentIdentifier textDocument,
            Position position,
            SignatureHelpContext? context = null,
            ProgressToken? workDoneToken = null
        )
        {
            Context = context;
            TextDocument = textDocument;
            Position = position;
            WorkDoneToken = workDoneToken;
        }
        /// <summary>
        /// The signature help context. This is only available if the client specifies
        /// to send this using the client capability `textDocument.signatureHelp.contextSupport === true`
        /// 
        /// </summary>
        [Since("3.15.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "context")]
        public SignatureHelpContext? Context { get; init; }
        /// <summary>
        /// The text document.
        /// </summary>
        [DataMember(Name = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; init; }
        /// <summary>
        /// The position inside the text document.
        /// </summary>
        [DataMember(Name = "position")]
        public Position Position { get; init; }
        /// <summary>
        /// An optional token that a server can use to report work done progress.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneToken")]
        public ProgressToken? WorkDoneToken { get; init; }
    }

}
