// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Client Capabilities for a <see cref="SignatureHelpRequest" />.
    /// </summary>
    [DataContract]
    public record SignatureHelpClientCapabilities
    {
        [JsonConstructor]
        public SignatureHelpClientCapabilities(
            bool? dynamicRegistration = null,
            ClientSignatureInformationOptions? signatureInformation = null,
            bool? contextSupport = null
        )
        {
            DynamicRegistration = dynamicRegistration;
            SignatureInformation = signatureInformation;
            ContextSupport = contextSupport;
        }
        /// <summary>
        /// Whether signature help supports dynamic registration.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "dynamicRegistration")]
        public bool? DynamicRegistration { get; init; }
        /// <summary>
        /// The client supports the following `SignatureInformation`
        /// specific properties.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "signatureInformation")]
        public ClientSignatureInformationOptions? SignatureInformation { get; init; }
        /// <summary>
        /// The client supports to send additional context information for a
        /// `textDocument/signatureHelp` request. A client that opts into
        /// contextSupport will also support the `retriggerCharacters` on
        /// `SignatureHelpOptions`.
        /// 
        /// </summary>
        [Since("3.15.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "contextSupport")]
        public bool? ContextSupport { get; init; }
    }

}
