// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record StaleRequestSupportOptions
    {
        [JsonConstructor]
        public StaleRequestSupportOptions(
            bool cancel,
            ImmutableArray<string> retryOnContentModified
        )
        {
            Cancel = cancel;
            RetryOnContentModified = retryOnContentModified;
        }
        /// <summary>
        /// The client will actively cancel the request.
        /// </summary>
        [DataMember(Name = "cancel")]
        public bool Cancel { get; init; }
        /// <summary>
        /// The list of requests for which the client
        /// will retry the request if it receives a
        /// response with error code `ContentModified`
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<string>))]
        [DataMember(Name = "retryOnContentModified")]
        public ImmutableArray<string> RetryOnContentModified { get; init; }
    }

}
