// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Request to request completion at a given text document position. The request's
    /// parameter is of type <see cref="TextDocumentPosition" /> the response
    /// is of type {@link CompletionItem CompletionItem[]} or <see cref="CompletionList" />
    /// or a Thenable that resolves to such.
    /// 
    /// The request can delay the computation of the <see cref="CompletionItem.detail">`detail`</see>
    /// and <see cref="CompletionItem.documentation">`documentation`</see> properties to the `completionItem/resolve`
    /// request. However, properties that are needed for the initial sorting and filtering, like `sortText`,
    /// `filterText`, `insertText`, and `textEdit`, must not be changed during resolve.
    /// </summary>
    [Direction(MessageDirection.ClientToServer)]
    [LSPRequest("textDocument/completion", typeof(TextDocumentCompletionResponse), typeof(ImmutableArray<CompletionItem>))]
    [DataContract]
    public record TextDocumentCompletionRequest: IRequest<CompletionParams>
    {
        [JsonConstructor]
        public TextDocumentCompletionRequest(
            OrType<string, int> id,
            string method,
            CompletionParams paramsValue,
            string jsonrpc = "2.0"
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Method = method;
            Params = paramsValue;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// The Request method.
        /// </summary>
        [DataMember(Name = "method")]
        public string Method { get; init; }
        /// <summary>
        /// The Request parameters.
        /// </summary>
        [DataMember(Name = "params")]
        public CompletionParams Params { get; init; }
    }

}
