// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Save registration options.
    /// </summary>
    [DataContract]
    public record TextDocumentSaveRegistrationOptions
    {
        [JsonConstructor]
        public TextDocumentSaveRegistrationOptions(
            DocumentSelector? documentSelector = null,
            bool? includeText = null
        )
        {
            DocumentSelector = documentSelector;
            IncludeText = includeText;
        }
        /// <summary>
        /// A document selector to identify the scope of the registration. If set to null
        /// the document selector provided on the client side will be used.
        /// </summary>
        [JsonConverter(typeof(DocumentSelectorConverter))]
        [DataMember(Name = "documentSelector")]
        public DocumentSelector? DocumentSelector { get; init; }
        /// <summary>
        /// The client is supposed to include the content on save.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "includeText")]
        public bool? IncludeText { get; init; }
    }

}
