// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A document filter where `scheme` is required field.
    /// 
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record TextDocumentFilterScheme
    {
        [JsonConstructor]
        public TextDocumentFilterScheme(
            string scheme,
            string? language = null,
            string? pattern = null
        )
        {
            Language = language;
            Scheme = scheme;
            Pattern = pattern;
        }
        /// <summary>
        /// A language id, like `typescript`.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "language")]
        public string? Language { get; init; }
        /// <summary>
        /// A Uri <see cref="Uri.scheme">scheme</see>, like `file` or `untitled`.
        /// </summary>
        [DataMember(Name = "scheme")]
        public string Scheme { get; init; }
        /// <summary>
        /// A glob pattern, like **​/*.{ts,js}. See TextDocumentFilter for examples.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "pattern")]
        public string? Pattern { get; init; }
    }

}
