// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A parameter literal used in requests to pass a text document and a position inside that
    /// document.
    /// </summary>
    [DataContract]
    public record TextDocumentPositionParams
    {
        [JsonConstructor]
        public TextDocumentPositionParams(
            TextDocumentIdentifier textDocument,
            Position position
        )
        {
            TextDocument = textDocument;
            Position = position;
        }
        /// <summary>
        /// The text document.
        /// </summary>
        [DataMember(Name = "textDocument")]
        public TextDocumentIdentifier TextDocument { get; init; }
        /// <summary>
        /// The position inside the text document.
        /// </summary>
        [DataMember(Name = "position")]
        public Position Position { get; init; }
    }

}
