// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A request to result a `TypeHierarchyItem` in a document at a given position.
    /// Can be used as an input to a subtypes or supertypes type hierarchy.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [Direction(MessageDirection.ClientToServer)]
    [LSPRequest("textDocument/prepareTypeHierarchy", typeof(TextDocumentPrepareTypeHierarchyResponse))]
    [DataContract]
    public record TextDocumentPrepareTypeHierarchyRequest: IRequest<TypeHierarchyPrepareParams>
    {
        [JsonConstructor]
        public TextDocumentPrepareTypeHierarchyRequest(
            OrType<string, int> id,
            string method,
            TypeHierarchyPrepareParams paramsValue,
            string jsonrpc = "2.0"
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Method = method;
            Params = paramsValue;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// The Request method.
        /// </summary>
        [DataMember(Name = "method")]
        public string Method { get; init; }
        /// <summary>
        /// The Request parameters.
        /// </summary>
        [DataMember(Name = "params")]
        public TypeHierarchyPrepareParams Params { get; init; }
    }

}
