// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A request to resolve project-wide references for the symbol denoted
    /// by the given text document position. The request's parameter is of
    /// type <see cref="ReferenceParams" /> the response is of type
    /// {@link Location Location[]} or a Thenable that resolves to such.
    /// </summary>
    [Direction(MessageDirection.ClientToServer)]
    [LSPRequest("textDocument/references", typeof(TextDocumentReferencesResponse), typeof(ImmutableArray<Location>))]
    [DataContract]
    public record TextDocumentReferencesRequest: IRequest<ReferenceParams>
    {
        [JsonConstructor]
        public TextDocumentReferencesRequest(
            OrType<string, int> id,
            string method,
            ReferenceParams paramsValue,
            string jsonrpc = "2.0"
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Method = method;
            Params = paramsValue;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// The Request method.
        /// </summary>
        [DataMember(Name = "method")]
        public string Method { get; init; }
        /// <summary>
        /// The Request parameters.
        /// </summary>
        [DataMember(Name = "params")]
        public ReferenceParams Params { get; init; }
    }

}
