// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A request to resolve the type definition locations of a symbol at a given text
    /// document position. The request's parameter is of type <see cref="TextDocumentPositionParams" />
    /// the response is of type <see cref="Declaration" /> or a typed array of <see cref="DeclarationLink" />
    /// or a Thenable that resolves to such.
    /// </summary>
    [Direction(MessageDirection.ClientToServer)]
    [LSPRequest("textDocument/declaration", typeof(TextDocumentDeclarationResponse), typeof(OrType<ImmutableArray<Location>, ImmutableArray<DeclarationLink>>))]
    [DataContract]
    public record TextDocumentDeclarationRequest: IRequest<DeclarationParams>
    {
        [JsonConstructor]
        public TextDocumentDeclarationRequest(
            OrType<string, int> id,
            string method,
            DeclarationParams paramsValue,
            string jsonrpc = "2.0"
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Method = method;
            Params = paramsValue;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// The Request method.
        /// </summary>
        [DataMember(Name = "method")]
        public string Method { get; init; }
        /// <summary>
        /// The Request parameters.
        /// </summary>
        [DataMember(Name = "params")]
        public DeclarationParams Params { get; init; }
    }

}
