// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A request to resolve the definition location of a symbol at a given text
    /// document position. The request's parameter is of type <see cref="TextDocumentPosition" />
    /// the response is of either type <see cref="Definition" /> or a typed array of
    /// <see cref="DefinitionLink" /> or a Thenable that resolves to such.
    /// </summary>
    [LSPResponse(typeof(TextDocumentDefinitionRequest))]
    [DataContract]
    public record TextDocumentDefinitionResponse: IResponse<OrType<Definition, ImmutableArray<DefinitionLink>>>
    {
        [JsonConstructor]
        public TextDocumentDefinitionResponse(
            OrType<string, int> id,
            string jsonrpc = "2.0",
            OrType<Definition, ImmutableArray<DefinitionLink>>? result = null,
            ResponseError? error = null
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Result = result;
            Error = error;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// Results for the request.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<Definition, ImmutableArray<DefinitionLink>>))]
        [DataMember(Name = "result")]
        public OrType<Definition, ImmutableArray<DefinitionLink>>? Result { get; init; }
        /// <summary>
        /// Error while handling the request.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "error")]
        public ResponseError? Error { get; init; }
    }

}
