// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// An item to transfer a text document from the client to the
    /// server.
    /// </summary>
    [DataContract]
    public record TextDocumentItem
    {
        [JsonConstructor]
        public TextDocumentItem(
            Uri uri,
            string languageId,
            int version,
            string text
        )
        {
            Uri = uri;
            LanguageId = languageId;
            Version = version;
            Text = text;
        }
        /// <summary>
        /// The text document's uri.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "uri")]
        public Uri Uri { get; init; }
        /// <summary>
        /// The text document's language identifier.
        /// </summary>
        [DataMember(Name = "languageId")]
        public string LanguageId { get; init; }
        /// <summary>
        /// The version number of this document (it will increase after each
        /// change, including undo/redo).
        /// </summary>
        [DataMember(Name = "version")]
        public int Version { get; init; }
        /// <summary>
        /// The content of the opened text document.
        /// </summary>
        [DataMember(Name = "text")]
        public string Text { get; init; }
    }

}
