// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record TextDocumentContentChangeWholeDocument
    {
        [JsonConstructor]
        public TextDocumentContentChangeWholeDocument(
            string text
        )
        {
            Text = text;
        }
        /// <summary>
        /// The new text of the whole document.
        /// </summary>
        [DataMember(Name = "text")]
        public string Text { get; init; }
    }

}
