// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;

namespace Microsoft.LanguageServer.Protocol {
    public class TextDocumentFilterConverter : JsonConverter<TextDocumentFilter>
    {
    private OrTypeConverter<TextDocumentFilterLanguage,TextDocumentFilterScheme,TextDocumentFilterPattern> _orType;
    public TextDocumentFilterConverter()
    {
    _orType = new OrTypeConverter<TextDocumentFilterLanguage,TextDocumentFilterScheme,TextDocumentFilterPattern>();
    }
    public override TextDocumentFilter? ReadJson(JsonReader reader, Type objectType, TextDocumentFilter? existingValue, bool hasExistingValue, JsonSerializer serializer)
    {
    reader = reader ?? throw new ArgumentNullException(nameof(reader));
    if (reader.TokenType == JsonToken.Null) { return null; }
    var o = _orType.ReadJson(reader, objectType, existingValue, serializer);
    if (o is OrType<TextDocumentFilterLanguage,TextDocumentFilterScheme,TextDocumentFilterPattern> orType)
    {
    if (orType.Value?.GetType() == typeof(TextDocumentFilterLanguage))
    {
    return new TextDocumentFilter((TextDocumentFilterLanguage)orType.Value);
    }
    if (orType.Value?.GetType() == typeof(TextDocumentFilterScheme))
    {
    return new TextDocumentFilter((TextDocumentFilterScheme)orType.Value);
    }
    if (orType.Value?.GetType() == typeof(TextDocumentFilterPattern))
    {
    return new TextDocumentFilter((TextDocumentFilterPattern)orType.Value);
    }
    }
    throw new JsonSerializationException($"Unexpected token type.");
    }
    public override void WriteJson(JsonWriter writer, TextDocumentFilter? value, JsonSerializer serializer)
    {
    _orType.WriteJson(writer, value, serializer);
    }
    }
}
