// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The parameter of a `typeHierarchy/supertypes` request.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record TypeHierarchySupertypesParams
    {
        [JsonConstructor]
        public TypeHierarchySupertypesParams(
            TypeHierarchyItem item,
            ProgressToken? workDoneToken = null,
            ProgressToken? partialResultToken = null
        )
        {
            Item = item;
            WorkDoneToken = workDoneToken;
            PartialResultToken = partialResultToken;
        }
        [DataMember(Name = "item")]
        public TypeHierarchyItem Item { get; init; }
        /// <summary>
        /// An optional token that a server can use to report work done progress.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneToken")]
        public ProgressToken? WorkDoneToken { get; init; }
        /// <summary>
        /// An optional token that a server can use to report partial results (e.g. streaming) to
        /// the client.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "partialResultToken")]
        public ProgressToken? PartialResultToken { get; init; }
    }

}
