// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record WindowClientCapabilities
    {
        [JsonConstructor]
        public WindowClientCapabilities(
            bool? workDoneProgress = null,
            ShowMessageRequestClientCapabilities? showMessage = null,
            ShowDocumentClientCapabilities? showDocument = null
        )
        {
            WorkDoneProgress = workDoneProgress;
            ShowMessage = showMessage;
            ShowDocument = showDocument;
        }
        /// <summary>
        /// It indicates whether the client supports server initiated
        /// progress using the `window/workDoneProgress/create` request.
        /// 
        /// The capability also controls Whether client supports handling
        /// of progress notifications. If set servers are allowed to report a
        /// `workDoneProgress` property in the request specific server
        /// capabilities.
        /// 
        /// </summary>
        [Since("3.15.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
        /// <summary>
        /// Capabilities specific to the showMessage request.
        /// 
        /// </summary>
        [Since("3.16.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "showMessage")]
        public ShowMessageRequestClientCapabilities? ShowMessage { get; init; }
        /// <summary>
        /// Capabilities specific to the showDocument request.
        /// 
        /// </summary>
        [Since("3.16.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "showDocument")]
        public ShowDocumentClientCapabilities? ShowDocument { get; init; }
    }

}
