// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Defines workspace specific capabilities of the server.
    /// 
    /// </summary>
    [Proposed]
    [Since("3.18.0")]
    [DataContract]
    public record WorkspaceOptions
    {
        [JsonConstructor]
        public WorkspaceOptions(
            WorkspaceFoldersServerCapabilities? workspaceFolders = null,
            FileOperationOptions? fileOperations = null
        )
        {
            WorkspaceFolders = workspaceFolders;
            FileOperations = fileOperations;
        }
        /// <summary>
        /// The server supports workspace folder.
        /// 
        /// </summary>
        [Since("3.6.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workspaceFolders")]
        public WorkspaceFoldersServerCapabilities? WorkspaceFolders { get; init; }
        /// <summary>
        /// The server is interested in notifications/requests for operations on files.
        /// 
        /// </summary>
        [Since("3.16.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "fileOperations")]
        public FileOperationOptions? FileOperations { get; init; }
    }

}
