// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Registration options for a <see cref="WorkspaceSymbolRequest" />.
    /// </summary>
    [DataContract]
    public record WorkspaceSymbolRegistrationOptions
    {
        [JsonConstructor]
        public WorkspaceSymbolRegistrationOptions(
            bool? resolveProvider = null,
            bool? workDoneProgress = null
        )
        {
            ResolveProvider = resolveProvider;
            WorkDoneProgress = workDoneProgress;
        }
        /// <summary>
        /// The server provides support to resolve additional
        /// information for a workspace symbol.
        /// 
        /// </summary>
        [Since("3.17.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "resolveProvider")]
        public bool? ResolveProvider { get; init; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workDoneProgress")]
        public bool? WorkDoneProgress { get; init; }
    }

}
