// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The will rename files request is sent from the client to the server before files are actually
    /// renamed as long as the rename is triggered from within the client.
    /// 
    /// </summary>
    [Since("3.16.0")]
    [Direction(MessageDirection.ClientToServer)]
    [LSPRequest("workspace/willRenameFiles", typeof(WorkspaceWillRenameFilesResponse))]
    [DataContract]
    public record WorkspaceWillRenameFilesRequest: IRequest<RenameFilesParams>
    {
        [JsonConstructor]
        public WorkspaceWillRenameFilesRequest(
            OrType<string, int> id,
            string method,
            RenameFilesParams paramsValue,
            string jsonrpc = "2.0"
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Method = method;
            Params = paramsValue;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// The Request method.
        /// </summary>
        [DataMember(Name = "method")]
        public string Method { get; init; }
        /// <summary>
        /// The Request parameters.
        /// </summary>
        [DataMember(Name = "params")]
        public RenameFilesParams Params { get; init; }
    }

}
