// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A partial result for a workspace diagnostic report.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record WorkspaceDiagnosticReportPartialResult
    {
        [JsonConstructor]
        public WorkspaceDiagnosticReportPartialResult(
            ImmutableArray<WorkspaceDocumentDiagnosticReport> items
        )
        {
            Items = items;
        }
        [JsonConverter(typeof(CustomArrayConverter<WorkspaceDocumentDiagnosticReport>))]
        [DataMember(Name = "items")]
        public ImmutableArray<WorkspaceDocumentDiagnosticReport> Items { get; init; }
    }

}
