// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record WorkDoneProgressEnd
    {
        [JsonConstructor]
        public WorkDoneProgressEnd(
            string kind,
            string? message = null
        )
        {
            Kind = kind;
            Message = message;
        }
        [DataMember(Name = "kind")]
        public string Kind { get; init; } = "end";
        /// <summary>
        /// Optional, a final message indicating to for example indicate the outcome
        /// of the operation.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "message")]
        public string? Message { get; init; }
    }

}
