// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A request send from the client to the server to execute a command. The request might return
    /// a workspace edit which the client will apply to the workspace.
    /// </summary>
    [Direction(MessageDirection.ClientToServer)]
    [LSPRequest("workspace/executeCommand", typeof(WorkspaceExecuteCommandResponse))]
    [DataContract]
    public record WorkspaceExecuteCommandRequest: IRequest<ExecuteCommandParams>
    {
        [JsonConstructor]
        public WorkspaceExecuteCommandRequest(
            OrType<string, int> id,
            string method,
            ExecuteCommandParams paramsValue,
            string jsonrpc = "2.0"
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Method = method;
            Params = paramsValue;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// The Request method.
        /// </summary>
        [DataMember(Name = "method")]
        public string Method { get; init; }
        /// <summary>
        /// The Request parameters.
        /// </summary>
        [DataMember(Name = "params")]
        public ExecuteCommandParams Params { get; init; }
    }

}
