// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// A full document diagnostic report for a workspace diagnostic result.
    /// 
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public record WorkspaceFullDocumentDiagnosticReport
    {
        [JsonConstructor]
        public WorkspaceFullDocumentDiagnosticReport(
            Uri uri,
            string kind,
            ImmutableArray<Diagnostic> items,
            int? version = null,
            string? resultId = null
        )
        {
            Uri = uri;
            Version = version;
            Kind = kind;
            ResultId = resultId;
            Items = items;
        }
        /// <summary>
        /// The URI for which diagnostic information is reported.
        /// </summary>
        [JsonConverter(typeof(CustomStringConverter<Uri>))]
        [DataMember(Name = "uri")]
        public Uri Uri { get; init; }
        /// <summary>
        /// The version number for which the diagnostics are reported.
        /// If the document is not marked as open `null` can be provided.
        /// </summary>
        [DataMember(Name = "version")]
        public int? Version { get; init; }
        /// <summary>
        /// A full document diagnostic report.
        /// </summary>
        [DataMember(Name = "kind")]
        public string Kind { get; init; } = "full";
        /// <summary>
        /// An optional result id. If provided it will
        /// be sent on the next diagnostic request for the
        /// same document.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "resultId")]
        public string? ResultId { get; init; }
        /// <summary>
        /// The actual items.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<Diagnostic>))]
        [DataMember(Name = "items")]
        public ImmutableArray<Diagnostic> Items { get; init; }
    }

}
