// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// Workspace specific client capabilities.
    /// </summary>
    [DataContract]
    public record WorkspaceClientCapabilities
    {
        [JsonConstructor]
        public WorkspaceClientCapabilities(
            bool? applyEdit = null,
            WorkspaceEditClientCapabilities? workspaceEdit = null,
            DidChangeConfigurationClientCapabilities? didChangeConfiguration = null,
            DidChangeWatchedFilesClientCapabilities? didChangeWatchedFiles = null,
            WorkspaceSymbolClientCapabilities? symbol = null,
            ExecuteCommandClientCapabilities? executeCommand = null,
            bool? workspaceFolders = null,
            bool? configuration = null,
            SemanticTokensWorkspaceClientCapabilities? semanticTokens = null,
            CodeLensWorkspaceClientCapabilities? codeLens = null,
            FileOperationClientCapabilities? fileOperations = null,
            InlineValueWorkspaceClientCapabilities? inlineValue = null,
            InlayHintWorkspaceClientCapabilities? inlayHint = null,
            DiagnosticWorkspaceClientCapabilities? diagnostics = null,
            FoldingRangeWorkspaceClientCapabilities? foldingRange = null
        )
        {
            ApplyEdit = applyEdit;
            WorkspaceEdit = workspaceEdit;
            DidChangeConfiguration = didChangeConfiguration;
            DidChangeWatchedFiles = didChangeWatchedFiles;
            Symbol = symbol;
            ExecuteCommand = executeCommand;
            WorkspaceFolders = workspaceFolders;
            Configuration = configuration;
            SemanticTokens = semanticTokens;
            CodeLens = codeLens;
            FileOperations = fileOperations;
            InlineValue = inlineValue;
            InlayHint = inlayHint;
            Diagnostics = diagnostics;
            FoldingRange = foldingRange;
        }
        /// <summary>
        /// The client supports applying batch edits
        /// to the workspace by supporting the request
        /// 'workspace/applyEdit'
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "applyEdit")]
        public bool? ApplyEdit { get; init; }
        /// <summary>
        /// Capabilities specific to `WorkspaceEdit`s.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workspaceEdit")]
        public WorkspaceEditClientCapabilities? WorkspaceEdit { get; init; }
        /// <summary>
        /// Capabilities specific to the `workspace/didChangeConfiguration` notification.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "didChangeConfiguration")]
        public DidChangeConfigurationClientCapabilities? DidChangeConfiguration { get; init; }
        /// <summary>
        /// Capabilities specific to the `workspace/didChangeWatchedFiles` notification.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "didChangeWatchedFiles")]
        public DidChangeWatchedFilesClientCapabilities? DidChangeWatchedFiles { get; init; }
        /// <summary>
        /// Capabilities specific to the `workspace/symbol` request.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "symbol")]
        public WorkspaceSymbolClientCapabilities? Symbol { get; init; }
        /// <summary>
        /// Capabilities specific to the `workspace/executeCommand` request.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "executeCommand")]
        public ExecuteCommandClientCapabilities? ExecuteCommand { get; init; }
        /// <summary>
        /// The client has support for workspace folders.
        /// 
        /// </summary>
        [Since("3.6.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "workspaceFolders")]
        public bool? WorkspaceFolders { get; init; }
        /// <summary>
        /// The client supports `workspace/configuration` requests.
        /// 
        /// </summary>
        [Since("3.6.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "configuration")]
        public bool? Configuration { get; init; }
        /// <summary>
        /// Capabilities specific to the semantic token requests scoped to the
        /// workspace.
        /// 
        /// </summary>
        [Since("3.16.0.")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "semanticTokens")]
        public SemanticTokensWorkspaceClientCapabilities? SemanticTokens { get; init; }
        /// <summary>
        /// Capabilities specific to the code lens requests scoped to the
        /// workspace.
        /// 
        /// </summary>
        [Since("3.16.0.")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "codeLens")]
        public CodeLensWorkspaceClientCapabilities? CodeLens { get; init; }
        /// <summary>
        /// The client has support for file notifications/requests for user operations on files.
        /// 
        /// Since 3.16.0
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "fileOperations")]
        public FileOperationClientCapabilities? FileOperations { get; init; }
        /// <summary>
        /// Capabilities specific to the inline values requests scoped to the
        /// workspace.
        /// 
        /// </summary>
        [Since("3.17.0.")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "inlineValue")]
        public InlineValueWorkspaceClientCapabilities? InlineValue { get; init; }
        /// <summary>
        /// Capabilities specific to the inlay hint requests scoped to the
        /// workspace.
        /// 
        /// </summary>
        [Since("3.17.0.")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "inlayHint")]
        public InlayHintWorkspaceClientCapabilities? InlayHint { get; init; }
        /// <summary>
        /// Capabilities specific to the diagnostic requests scoped to the
        /// workspace.
        /// 
        /// </summary>
        [Since("3.17.0.")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "diagnostics")]
        public DiagnosticWorkspaceClientCapabilities? Diagnostics { get; init; }
        /// <summary>
        /// Capabilities specific to the folding range requests scoped to the workspace.
        /// 
        /// </summary>
        [Proposed]
        [Since("3.18.0")]
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "foldingRange")]
        public FoldingRangeWorkspaceClientCapabilities? FoldingRange { get; init; }
    }

}
