// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record WorkspaceFoldersInitializeParams
    {
        [JsonConstructor]
        public WorkspaceFoldersInitializeParams(
            ImmutableArray<WorkspaceFolder> workspaceFolders = default!
        )
        {
            WorkspaceFolders = workspaceFolders;
        }
        /// <summary>
        /// The workspace folders configured in the client when the server starts.
        /// 
        /// This property is only available if the client supports workspace folders.
        /// It can be `null` if the client supports workspace folders but none are
        /// configured.
        /// 
        /// </summary>
        [Since("3.6.0")]
        [JsonConverter(typeof(CustomArrayConverter<WorkspaceFolder>))]
        [DataMember(Name = "workspaceFolders")]
        public ImmutableArray<WorkspaceFolder> WorkspaceFolders { get; init; }
    }

}
