// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    [DataContract]
    public record WorkDoneProgressReport
    {
        [JsonConstructor]
        public WorkDoneProgressReport(
            string kind,
            bool? cancellable = null,
            string? message = null,
            long? percentage = null
        )
        {
            Kind = kind;
            Cancellable = cancellable;
            Message = message;
            Percentage = percentage;
        }
        [DataMember(Name = "kind")]
        public string Kind { get; init; } = "report";
        /// <summary>
        /// Controls enablement state of a cancel button.
        /// 
        /// Clients that don't support cancellation or don't support controlling the button's
        /// enablement state are allowed to ignore the property.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "cancellable")]
        public bool? Cancellable { get; init; }
        /// <summary>
        /// Optional, more detailed associated progress message. Contains
        /// complementary information to the `title`.
        /// 
        /// Examples: "3/25 files", "project/src/module2", "node_modules/some_dep".
        /// If unset, the previous progress message (if any) is still valid.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "message")]
        public string? Message { get; init; }
        /// <summary>
        /// Optional progress percentage to display (value 100 is considered 100%).
        /// If not provided infinite progress is assumed and clients are allowed
        /// to ignore the `percentage` value in subsequent in report notifications.
        /// 
        /// The value should be steadily rising. Clients are free to ignore values
        /// that are not following this rule. The value range is [0, 100]
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "percentage")]
        public long? Percentage { get => percentage; set => percentage = Validators.validUInteger(value); }
        private long? percentage;
    }

}
