// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Collections.Immutable;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The 'workspace/configuration' request is sent from the server to the client to fetch a certain
    /// configuration setting.
    /// 
    /// This pull model replaces the old push model were the client signaled configuration change via an
    /// event. If the server still needs to react to configuration changes (since the server caches the
    /// result of `workspace/configuration` requests) the server should register for an empty configuration
    /// change event and empty the cache if such an event is received.
    /// </summary>
    [LSPResponse(typeof(WorkspaceConfigurationRequest))]
    [DataContract]
    public record WorkspaceConfigurationResponse: IResponse<ImmutableArray<LSPAny>>
    {
        [JsonConstructor]
        public WorkspaceConfigurationResponse(
            OrType<string, int> id,
            string jsonrpc = "2.0",
            ImmutableArray<LSPAny> result = default!,
            ResponseError? error = null
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Result = result;
            Error = error;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// Results for the request.
        /// </summary>
        [JsonConverter(typeof(CustomArrayConverter<LSPAny>))]
        [DataMember(Name = "result")]
        public ImmutableArray<LSPAny> Result { get; init; }
        /// <summary>
        /// Error while handling the request.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        [DataMember(Name = "error")]
        public ResponseError? Error { get; init; }
    }

}
