// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Microsoft.LanguageServer.Protocol {
    /// <summary>
    /// The 'workspace/configuration' request is sent from the server to the client to fetch a certain
    /// configuration setting.
    /// 
    /// This pull model replaces the old push model were the client signaled configuration change via an
    /// event. If the server still needs to react to configuration changes (since the server caches the
    /// result of `workspace/configuration` requests) the server should register for an empty configuration
    /// change event and empty the cache if such an event is received.
    /// </summary>
    [Direction(MessageDirection.ServerToClient)]
    [LSPRequest("workspace/configuration", typeof(WorkspaceConfigurationResponse))]
    [DataContract]
    public record WorkspaceConfigurationRequest: IRequest<ConfigurationParams>
    {
        [JsonConstructor]
        public WorkspaceConfigurationRequest(
            OrType<string, int> id,
            string method,
            ConfigurationParams paramsValue,
            string jsonrpc = "2.0"
        )
        {
            JsonRPC = jsonrpc;
            Id = id;
            Method = method;
            Params = paramsValue;
        }
        /// <summary>
        /// The jsonrpc version.
        /// </summary>
        [DataMember(Name = "jsonrpc")]
        public string JsonRPC { get; init; } = "2.0";
        /// <summary>
        /// The Request id.
        /// </summary>
        [JsonConverter(typeof(OrTypeConverter<string, int>))]
        [DataMember(Name = "id")]
        public OrType<string, int> Id { get; init; }
        /// <summary>
        /// The Request method.
        /// </summary>
        [DataMember(Name = "method")]
        public string Method { get; init; }
        /// <summary>
        /// The Request parameters.
        /// </summary>
        [DataMember(Name = "params")]
        public ConfigurationParams Params { get; init; }
    }

}
